# Generated by Django 4.2.7 on 2023-12-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bills',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
