# Generated by Django 4.2.7 on 2023-12-12 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transientpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transientpayment',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
