# Generated by Django 4.2.7 on 2023-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
