# Generated by Django 4.2.7 on 2023-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='payments',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
