# Generated by Django 4.2.7 on 2023-11-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0001_initial'),
        ('tenants', '0002_remove_tenant_address_remove_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardinghouse.room'),
        ),
    ]
