# Generated by Django 4.2.7 on 2023-11-17 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
