# Generated by Django 4.2.7 on 2023-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_tenant_boardinghouse_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
