# Generated by Django 4.2.7 on 2023-11-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='balance',
            new_name='current_balance',
        ),
        migrations.AddField(
            model_name='tenant',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
