# Generated by Django 4.2.7 on 2023-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_rename_balance_tenant_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
