# Generated by Django 4.2.7 on 2023-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='add_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
