# Generated by Django 4.2.7 on 2023-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_add_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
