# Generated by Django 4.2.7 on 2023-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
