# Generated by Django 4.2.7 on 2023-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_feedback_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
