# Generated by Django 4.2.7 on 2023-12-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_notice_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
