# Generated by Django 4.2.7 on 2023-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_notice_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
