# Generated by Django 4.2.7 on 2023-11-16 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('image', models.ImageField(blank=True, upload_to='boardinghouse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardinghouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_bed', models.IntegerField()),
                ('male_female', models.CharField(choices=[('For Male Only', 'For Male Only'), ('For Female Only', 'For Female Only'), ('For Both Male and Female', 'For Both Male and Female')], max_length=50)),
                ('vacant', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='room')),
                ('boardinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='boardinghouse.boardinghouse')),
            ],
        ),
    ]
