# Generated by Django 4.2.7 on 2023-12-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='boardinghouse')),
                ('boardinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boardinghouse.boardinghouse')),
            ],
        ),
    ]
