# Generated by Django 4.2.7 on 2023-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0002_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
