# Generated by Django 4.2.7 on 2023-11-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0002_boardinghouse_latitude_boardinghouse_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='latitude',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='longitude',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
    ]
