# Generated by Django 4.2.7 on 2023-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0003_alter_boardinghouse_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
