# Generated by Django 4.2.7 on 2023-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0004_alter_boardinghouse_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, upload_to='boardinghouse'),
        ),
    ]
