# Generated by Django 4.2.7 on 2023-11-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardinghouse', '0005_boardinghouse_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_bed', models.IntegerField()),
                ('male_female', models.CharField(choices=[('For Male Only', 'For Male Only'), ('For Female Only', 'For Female Only'), ('For Both Male and Female', 'For Both Male and Female')], max_length=50)),
                ('vacant', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='room')),
                ('boardinghouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='boardinghouse.boardinghouse')),
            ],
        ),
    ]
